# Generated by Django 5.1.2 on 2024-10-17 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiaAccActiveMetabolicMass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('s_score', models.FloatField()),
                ('skel_m', models.FloatField()),
                ('fm', models.FloatField()),
                ('imat', models.FloatField()),
                ('aat', models.FloatField()),
                ('le', models.FloatField()),
                ('gly', models.FloatField()),
                ('vi_org', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'bia_acc_active_metabolic_mass',
            },
        ),
        migrations.CreateModel(
            name='BiaAccBodyComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('ffm', models.FloatField()),
                ('brm', models.FloatField()),
                ('ecm', models.FloatField()),
                ('hpa_axir', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'bia_acc_body_composition',
            },
        ),
        migrations.CreateModel(
            name='BiaAccBone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('bo_dens', models.FloatField()),
                ('bone', models.FloatField()),
                ('t_score', models.FloatField()),
                ('bm', models.FloatField()),
                ('tbca', models.FloatField()),
                ('bbuffer', models.FloatField()),
                ('tbmg', models.FloatField()),
                ('tbp', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'bia_acc_bone',
            },
        ),
        migrations.CreateModel(
            name='BiaAccProteins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('tbprot', models.FloatField()),
                ('bcmprot', models.FloatField()),
                ('ecfprot', models.FloatField()),
                ('ecmprot', models.FloatField()),
                ('le', models.FloatField()),
                ('cr_24h', models.FloatField()),
                ('stm', models.FloatField()),
                ('gly_free', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'bia_acc_proteins',
            },
        ),
        migrations.CreateModel(
            name='BiaAccSoftTissueMineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('tbk', models.FloatField()),
                ('eck', models.FloatField()),
                ('tbna', models.FloatField()),
                ('tbcl', models.FloatField()),
                ('o_pral', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'bia_acc_soft_tissue _mineral',
            },
        ),
        migrations.CreateModel(
            name='BiaAccWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('tbw', models.FloatField()),
                ('scam_to', models.FloatField()),
                ('ecw', models.FloatField()),
                ('icw', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'bia_acc_water',
            },
        ),
        migrations.CreateModel(
            name='HEG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('rcbo2', models.FloatField()),
                ('sd', models.FloatField()),
                ('slope', models.FloatField()),
                ('cbf_ratio', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'heg',
            },
        ),
        migrations.CreateModel(
            name='PPGStressFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('sdnn', models.FloatField()),
                ('rmssd', models.FloatField()),
                ('c_rer', models.FloatField()),
                ('thm_pw', models.FloatField()),
                ('lf_vlf_le', models.FloatField()),
                ('lf_vlf_ri', models.FloatField()),
                ('me_hr', models.FloatField()),
                ('hrv_min', models.FloatField()),
                ('hrv_max', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'ppg_stress_flow',
            },
        ),
    ]
