# Generated by Django 5.1.2 on 2024-10-18 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_biaaccactivemetabolicmass_biaaccbodycomposition_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='biaaccsofttissuemineral',
            table='bia_acc_soft_tissue_mineral',
        ),
    ]
