# Generated by Django 5.1.2 on 2024-10-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_biaaccsofttissuemineral_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biaaccactivemetabolicmass',
            name='aat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccactivemetabolicmass',
            name='fm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccactivemetabolicmass',
            name='gly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccactivemetabolicmass',
            name='imat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccactivemetabolicmass',
            name='le',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccactivemetabolicmass',
            name='s_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccactivemetabolicmass',
            name='skel_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccactivemetabolicmass',
            name='vi_org',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccbodycomposition',
            name='brm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccbodycomposition',
            name='ecm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccbodycomposition',
            name='ffm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccbone',
            name='bbuffer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccbone',
            name='bm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccbone',
            name='bo_dens',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccbone',
            name='bone',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccbone',
            name='t_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccbone',
            name='tbca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccbone',
            name='tbmg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccbone',
            name='tbp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccproteins',
            name='bcmprot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccproteins',
            name='cr_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccproteins',
            name='ecfprot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccproteins',
            name='ecmprot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccproteins',
            name='gly_free',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccproteins',
            name='le',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccproteins',
            name='stm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccproteins',
            name='tbprot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccsofttissuemineral',
            name='eck',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccsofttissuemineral',
            name='o_pral',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccsofttissuemineral',
            name='tbcl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccsofttissuemineral',
            name='tbk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccsofttissuemineral',
            name='tbna',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccwater',
            name='ecw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccwater',
            name='icw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccwater',
            name='scam_to',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biaaccwater',
            name='tbw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heg',
            name='cbf_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heg',
            name='rcbo2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heg',
            name='sd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heg',
            name='slope',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppgstressflow',
            name='c_rer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppgstressflow',
            name='hrv_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppgstressflow',
            name='hrv_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppgstressflow',
            name='lf_vlf_le',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppgstressflow',
            name='lf_vlf_ri',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppgstressflow',
            name='me_hr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppgstressflow',
            name='rmssd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppgstressflow',
            name='sdnn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppgstressflow',
            name='thm_pw',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
