# Generated by Django 5.1.2 on 2024-10-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_patient_email_patient_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
